'use client'
import { useRef, useState } from 'react'
import { useAgentStore } from '@/store/agentStore'

const FORMATS = [
  { id: 'md',   label: 'Markdown',    ext: '.md',   icon: '⬇' },
  { id: 'txt',  label: 'Plain Text',  ext: '.txt',  icon: '📄' },
  { id: 'html', label: 'HTML',        ext: '.html', icon: '🌐' },
  { id: 'pdf',  label: 'PDF (Print)', ext: '.pdf',  icon: '📑' },
] as const

type FormatId = typeof FORMATS[number]['id']

export default function ReportPanel() {
  const reportMd  = useAgentStore((s) => s.reportMd)
  const avgCred   = useAgentStore((s) => s.avgCred)
  const topic     = useAgentStore((s) => s.topic)
  const webDocs   = useAgentStore((s) => s.webDocs)
  const intDocs   = useAgentStore((s) => s.intDocs)
  const elapsed   = useAgentStore((s) => s.elapsed)
  const [dropOpen, setDropOpen] = useState(false)
  const dropRef = useRef<HTMLDivElement>(null)

  if (!reportMd) return null

  const credNum    = parseFloat(avgCred)
  const credColor  = credNum >= 0.75 ? 'var(--green)' : credNum >= 0.5 ? 'var(--yellow)' : 'var(--red)'
  const credLabel  = credNum >= 0.75 ? 'Strong'   : credNum >= 0.5 ? 'Moderate' : 'Limited'
  const credDetail = credNum >= 0.75
    ? 'Sources are recent and from authoritative domains'
    : credNum >= 0.5
    ? 'Mix of reliable and lower-quality sources'
    : 'Limited reliable sources found — treat with caution'

  const totalSources = webDocs + intDocs
  const now = new Date().toLocaleDateString('en-US', {
    month: 'long', day: 'numeric', year: 'numeric',
  })

  function stripHtml(html: string) {
    return html.replace(/<[^>]+>/g, '').replace(/\n{3,}/g, '\n\n').trim()
  }

  function htmlToMarkdown(html: string) {
    return html
      .replace(/<h1[^>]*>(.*?)<\/h1>/gi, '# $1\n')
      .replace(/<h2[^>]*>(.*?)<\/h2>/gi, '## $1\n')
      .replace(/<h3[^>]*>(.*?)<\/h3>/gi, '### $1\n')
      .replace(/<strong[^>]*>(.*?)<\/strong>/gi, '**$1**')
      .replace(/<em[^>]*>(.*?)<\/em>/gi, '_$1_')
      .replace(/<code[^>]*>(.*?)<\/code>/gi, '`$1`')
      .replace(/<li[^>]*>(.*?)<\/li>/gi, '- $1\n')
      .replace(/<p[^>]*>(.*?)<\/p>/gi, '$1\n\n')
      .replace(/<br\s*\/?>/gi, '\n')
      .replace(/<[^>]+>/g, '')
      .replace(/\n{3,}/g, '\n\n')
      .trim()
  }

  function buildFullHtml() {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${topic || 'CI Report'}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 780px; margin: 40px auto; color: #1a1a2e; line-height: 1.7; padding: 0 20px; }
    h1 { font-size: 22px; font-weight: 700; border-bottom: 2px solid #eee; padding-bottom: 12px; }
    h2 { font-size: 15px; font-weight: 700; margin-top: 28px; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 12px; }
    th { background: #f5f5f5; padding: 8px 10px; text-align: left; font-size: 11px; }
    td { padding: 8px 10px; border-bottom: 1px solid #eee; }
    .meta { color: #666; font-size: 12px; margin-bottom: 20px; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #eee; font-size: 11px; color: #999; display: flex; justify-content: space-between; }
  </style>
</head>
<body>
  <p class="meta">Research Report · ${now} · ${totalSources} sources · ${credLabel} quality</p>
  <h1>${topic || 'Competitive Intelligence Report'}</h1>
  ${reportMd}
  <div class="footer">
    <span>Generated by CI Researcher · ${now}</span>
    <span>${totalSources} sources · ${credLabel} quality</span>
  </div>
</body>
</html>`
  }

  function download(formatId: FormatId) {
    setDropOpen(false)
    const filename = `ci-report-${Date.now()}`

    if (formatId === 'pdf') {
      const printWin = window.open('', '_blank')
      if (!printWin) return
      printWin.document.write(buildFullHtml())
      printWin.document.close()
      printWin.focus()
      setTimeout(() => { printWin.print(); printWin.close() }, 400)
      return
    }

    let content = ''
    let mime    = 'text/plain'
    let ext     = '.txt'

    if (formatId === 'md')   { content = `# ${topic || 'CI Report'}\n\n_${now} · ${totalSources} sources · ${credLabel} quality_\n\n${htmlToMarkdown(reportMd)}`; mime = 'text/markdown'; ext = '.md' }
    if (formatId === 'txt')  { content = `${topic || 'CI Report'}\n${now} · ${totalSources} sources · ${credLabel} quality\n\n${stripHtml(reportMd)}`;           mime = 'text/plain';    ext = '.txt' }
    if (formatId === 'html') { content = buildFullHtml();                                                                                                         mime = 'text/html';     ext = '.html' }

    const blob = new Blob([content], { type: mime })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = filename + ext
    a.click()
    URL.revokeObjectURL(url)
  }

  function handleCopy() {
    navigator.clipboard.writeText(htmlToMarkdown(reportMd))
  }

  return (
    <div className="fade-in" style={{ maxWidth: 760, margin: '0 auto' }}>

      {/* Document header */}
      <div style={{ borderBottom: '1px solid var(--border)', paddingBottom: 20, marginBottom: 24 }}>
        <div style={{
          fontSize: 10, fontWeight: 700, textTransform: 'uppercase',
          letterSpacing: '.8px', color: 'var(--text3)', marginBottom: 10,
          display: 'flex', alignItems: 'center', gap: 6,
        }}>
          <span style={{ display: 'inline-block', width: 6, height: 6, borderRadius: '50%', background: 'var(--green)' }} />
          Research Report · {now}
        </div>

        <h1 style={{ fontSize: 20, fontWeight: 700, color: 'var(--text)', lineHeight: 1.3, marginBottom: 16 }}>
          {topic || 'Competitive Intelligence Report'}
        </h1>

        <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 8 }}>
          <div style={{
            display: 'flex', alignItems: 'center', gap: 7,
            padding: '6px 12px', borderRadius: 20,
            background: `${credColor}12`, border: `1px solid ${credColor}30`,
          }}>
            <span style={{ fontSize: 12 }}>{credNum >= 0.75 ? '✓' : credNum >= 0.5 ? '~' : '⚠'}</span>
            <span style={{ fontSize: 11, fontWeight: 700, color: credColor }}>{credLabel} source quality</span>
          </div>

          {totalSources > 0 && (
            <div style={{ padding: '6px 12px', borderRadius: 20, background: 'var(--surface2)', border: '1px solid var(--border2)', fontSize: 11, color: 'var(--text2)' }}>
              {webDocs > 0 && `${webDocs} web source${webDocs !== 1 ? 's' : ''}`}
              {webDocs > 0 && intDocs > 0 && ' · '}
              {intDocs > 0 && `${intDocs} internal doc${intDocs !== 1 ? 's' : ''}`}
            </div>
          )}

          {elapsed && elapsed !== '—' && (
            <div style={{ padding: '6px 12px', borderRadius: 20, background: 'var(--surface2)', border: '1px solid var(--border2)', fontSize: 11, color: 'var(--text3)' }}>
              ⏱ {elapsed}
            </div>
          )}
        </div>

        <div style={{ marginTop: 10, fontSize: 11, color: 'var(--text3)', lineHeight: 1.5 }}>
          {credDetail}
        </div>
      </div>

      {/* Action bar */}
      <div style={{ display: 'flex', gap: 8, marginBottom: 28, alignItems: 'center' }}>

        {/* Download with format picker */}
        <div ref={dropRef} style={{ position: 'relative' }}>
          <div style={{ display: 'flex' }}>
            {/* Main download button */}
            <button
              onClick={() => download('md')}
              style={{
                display: 'flex', alignItems: 'center', gap: 6,
                padding: '7px 12px', borderRadius: '7px 0 0 7px',
                background: 'var(--surface2)',
                border: '1px solid var(--border2)',
                borderRight: 'none',
                fontSize: 11, fontWeight: 600,
                color: 'var(--text2)', cursor: 'pointer',
                transition: 'all .15s',
              }}
              onMouseEnter={(e) => { e.currentTarget.style.borderColor = 'var(--accent)'; e.currentTarget.style.color = 'var(--accent)' }}
              onMouseLeave={(e) => { e.currentTarget.style.borderColor = 'var(--border2)'; e.currentTarget.style.color = 'var(--text2)' }}
            >
              ⬇ Download .md
            </button>

            {/* Chevron to open format picker */}
            <button
              onClick={() => setDropOpen((v) => !v)}
              style={{
                padding: '7px 9px', borderRadius: '0 7px 7px 0',
                background: dropOpen ? 'rgba(91,127,255,.1)' : 'var(--surface2)',
                border: `1px solid ${dropOpen ? 'var(--accent)' : 'var(--border2)'}`,
                fontSize: 10, color: dropOpen ? 'var(--accent)' : 'var(--text3)',
                cursor: 'pointer', transition: 'all .15s',
              }}
            >
              {dropOpen ? '▲' : '▼'}
            </button>
          </div>

          {/* Format dropdown */}
          {dropOpen && (
            <div style={{
              position: 'absolute', top: 38, left: 0, zIndex: 50,
              background: 'var(--surface)', border: '1px solid var(--border2)',
              borderRadius: 8, overflow: 'hidden',
              boxShadow: '0 8px 24px rgba(0,0,0,.3)',
              minWidth: 180,
              animation: 'fadeIn .15s ease',
            }}>
              <div style={{ padding: '6px 10px 4px', fontSize: 9, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '.6px', color: 'var(--text3)' }}>
                Choose format
              </div>
              {FORMATS.map((f) => (
                <button
                  key={f.id}
                  onClick={() => download(f.id)}
                  style={{
                    width: '100%', display: 'flex', alignItems: 'center', gap: 9,
                    padding: '8px 12px', background: 'transparent',
                    border: 'none', cursor: 'pointer',
                    fontSize: 12, color: 'var(--text2)',
                    transition: 'background .1s', textAlign: 'left',
                  }}
                  onMouseEnter={(e) => e.currentTarget.style.background = 'var(--surface2)'}
                  onMouseLeave={(e) => e.currentTarget.style.background = 'transparent'}
                >
                  <span style={{ fontSize: 14, width: 20, textAlign: 'center' }}>{f.icon}</span>
                  <div>
                    <div style={{ fontWeight: 600 }}>{f.label}</div>
                    <div style={{ fontSize: 10, color: 'var(--text3)' }}>{f.ext}</div>
                  </div>
                </button>
              ))}
            </div>
          )}
        </div>

        <ActionBtn icon="⎘" label="Copy text" onClick={handleCopy} />
      </div>

      {/* Report body */}
      <div
        style={{ fontSize: 13, lineHeight: 1.8, color: 'var(--text2)' }}
        dangerouslySetInnerHTML={{ __html: injectDocStyles(reportMd) }}
      />

      {/* Footer */}
      <div style={{
        marginTop: 40, paddingTop: 16,
        borderTop: '1px solid var(--border)',
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
      }}>
        <span style={{ fontSize: 10, color: 'var(--text3)' }}>Generated by CI Researcher · {now}</span>
        <span style={{ fontSize: 10, color: 'var(--text3)' }}>{totalSources} sources · {credLabel} quality</span>
      </div>
    </div>
  )
}

function ActionBtn({ icon, label, onClick }: { icon: string; label: string; onClick: () => void }) {
  return (
    <button
      onClick={onClick}
      style={{
        display: 'flex', alignItems: 'center', gap: 6,
        padding: '7px 14px', borderRadius: 7,
        background: 'var(--surface2)', border: '1px solid var(--border2)',
        fontSize: 11, fontWeight: 600, color: 'var(--text2)',
        cursor: 'pointer', transition: 'all .15s',
      }}
      onMouseEnter={(e) => { e.currentTarget.style.borderColor = 'var(--accent)'; e.currentTarget.style.color = 'var(--accent)' }}
      onMouseLeave={(e) => { e.currentTarget.style.borderColor = 'var(--border2)'; e.currentTarget.style.color = 'var(--text2)' }}
    >
      <span>{icon}</span> {label}
    </button>
  )
}

function injectDocStyles(html: string): string {
  return html
    .replace(/<h2([^>]*)>/g, `<h2$1 style="font-size:15px;font-weight:700;color:var(--text);margin:28px 0 10px;padding-bottom:6px;border-bottom:1px solid var(--border)">`)
    .replace(/<table([^>]*)>/g, `<table$1 style="width:100%;border-collapse:collapse;margin:12px 0;font-size:12px">`)
    .replace(/<th([^>]*)>/g, `<th$1 style="padding:8px 10px;text-align:left;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.5px;color:var(--text3);border-bottom:2px solid var(--border2);background:var(--surface2)">`)
    .replace(/<td([^>]*)>/g, `<td$1 style="padding:8px 10px;border-bottom:1px solid var(--border);vertical-align:top">`)
    .replace(/<p([^>]*)>/g, `<p$1 style="margin:0 0 12px;line-height:1.8">`)
    .replace(/<strong([^>]*)>/g, `<strong$1 style="font-weight:700;color:var(--text)">`)
    .replace(/<code([^>]*)>/g, `<code$1 style="font-family:JetBrains Mono,monospace;font-size:11px;background:var(--surface2);border:1px solid var(--border2);border-radius:3px;padding:1px 5px">`)
}